config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tweets do
    resources :reactions, only: %i[create destroy]
  end

  resources :comments, only: %i[new create destroy]

  resources :users, only: %i[index show] do
    resources :follows, only: %i[create destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
    validates :description, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"
  # The user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"

end

app/models/reaction.rb
class Reaction < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
    enum status: [:like, :dislike, :not_set]

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    has_many :tweets, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy
    # Will return an array of follows for the given user instance
    has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"

    # Will return an array of users who follow the user instance
    has_many :followers, through: :received_follows, source: :follower
    # returns an array of follows a user gave to someone else
    has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
    
    # returns an array of other users who the user has followed
    has_many :followings, through: :given_follows, source: :followed_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @tweet = Tweet.find_by(id: params[:comment][:tweet_id])
    if @tweet.present?
      if @comment.save
        flash[:notice] = "Tweet was created successfully."
      end
    end 
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    return unless current_user.id == @comment.user_id
    @comment.destroy if @comment.present?
    flash[:success] = 'Comment deleted'
    redirect_to tweets_path
  end
  
  private

  def comment_params
    params.require(:comment).permit(:description, :tweet_id)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :get_follow, only: [:destroy]
  
  def create
    if !already_followed?
      if user_params.to_i != current_user.id
        Follow.create(follower_id: current_user.id, followed_user_id: user_params)
      else
       flash[:alert] = "Can not follow self."
      end
    end
  end

  def destroy
    @follow.destroy if already_followed?
  end

  private
  def already_followed?
    Follow.find_by(follower_id: current_user.id ,followed_user_id: params[:id]).present?
  end

  def get_follow
    @follow = Follow.find_by(follower_id: current_user.id ,followed_user_id: params[:id])
  end

  def user_params 
    params.require(:user_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
   before_action :find_tweet, only: [:create :destroy]
   before_action :find_reaction, only: [:destroy]
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @tweet.reactions.create(user_id: current_user.id)
    end
    redirect_to tweet_path(@tweet)
  end
  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @reaction.destroy
    end
    redirect_to tweet_path(@tweet)
  end

  private
  def find_tweet
    @tweet = Tweet.find_by(id: params[:tweet_id])
  end

  def already_liked?
    Reaction.where(user_id: current_user.id, tweet_id:
    params[:tweet_id]).exists?
  end

  def find_reaction
    @reaction = @tweet.reactions.find_by(id: params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  def show
    @comment = Comment.new
  end

  def index
    @tweets = Tweet.all
    @comment = Comment.new
  end

  def new
    @tweet = Tweet.new
  end

  def edit

  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = "Tweet was created successfully."
      redirect_to @tweet
    else
      render 'new'
    end
  end

  def update
    if @tweet.update(tweet_params)
      flash[:notice] = "Tweet was updated successfully."
      redirect_to @tweet
    else
      render 'edit'
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path
  end

 private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
  
  def tweet_params
    params.require(:tweet).permit(:title, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index 
        @users = User.all
    end

    def show
        @user = User.find_by(id: params[:id])
        @follows = Follow.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, id: "new-comment", remote: true do |f| %>
  <%= render "devise/shared/error_messages", resource: @comment %>
  <%= f.hidden_field :tweet_id, :value => object.id %>
  <div class="form-group">
    <%= f.text_area :description, class: "comment-box", placeholder: "Type your comment..." %>
  </div>
  <div>
    <%= f.submit 'Comment', class:"btn bg-secondary m-0" %>
  </div>
<% end %>

app/views/comments/_show_comment.html.erb
<li class="comment-box cards"><%= object.description %> <span><%= link_to image_tag("icons8-delete.svg", height: 25), comment_path(object), class:"px-3", remote: true, method: :delete, data: { confirm: "Are you sure?"} %> </span> </li>

app/views/comments/create.html.erb
<%= @comment.description %>

app/views/comments/create.js.erb
$("#tweet-<%= @tweet.id %>-comments-container").prepend(
  "<%= j render partial: 'comments/show_comment', locals: { object: @comment } %>"
);

app/views/home/index.html.erb
<%= render 'shared/navbar' %>
<div class="home-img">
  <div class="jumbotron" style="height: 780px">
    <div class="container text-center">
      <p></p>
      <h1>Twitter app</h1>
    </div>
    <p class="container text-center mt-5">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Est, doloribus?
      Impedit tenetur eaque amet corrupti culpa! Quae eos nam quas, porro, ex
      tempora eaque placeat nesciunt reprehenderit, ullam deleniti corrupti?
    </p>
    <div class="d-flex align-items-center justify-content-center mt-5 pt-5">
      <%= link_to "Sign up!", new_user_registration_path, class: "btn
      btn-success btn-lg" %>
    </div>
  </div>
</div>

<div class="card text-center">
  <div class="card-body">
    <h5 class="card-title">Contact Us</h5>
    <p class="card-text">Mail On the E-Mail ID or Open the link below</p>
    <a href="#" class="btn btn-primary">Chat</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if !user_signed_in? %>
            <li>
            <%= link_to "Sign in!", new_user_session_path, class: "dropdown-item" %>
            </li>
            <% end %>
            <% if user_signed_in? %>
            <li>
            <%= link_to "#{current_user.name}", user_path(current_user), class: "dropdown-item" %>
            </li>
            <% end%>
            <li><hr class="dropdown-divider"></li>
            <% if user_signed_in? %>
            <li>
            <%= link_to "Sign out!", destroy_user_session_path, :method => :delete , class: "dropdown-item" %>
            </li>
            <% else%>
            <li>
            <%= link_to "Sign up!", new_user_registration_path, class: "dropdown-item" %>
            </li>
            <% end %>
          </ul>
        </li>
      
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/tweets/edit.html.erb
<%= render 'shared/navbar' %>

<h1 class="text-center">Create new Tweet</h1>
<div class="card text-center">
 

   <%= form_with(model: @tweet, local: true ) do |f| %>
  <div class="card-header">
    User:
  </div>
  <div class="card-body">
    <h5 class="card-title">
    <%= f.label :title, class: "col-1 col-form-label text-left" %> 
        
    <%= f.text_field :title, class: "col-6 col-form-label" %>
        
    </h5>
    <p class="card-text"> 
    <%= f.label :description, class: "col-2 col-form-label align-top" %>
           
    <%= f.text_area :description, rows: 8, class: "col-8 col-form-label" %>

    </p>
    <p><%= f.submit class:"btn btn-primary"%></p>
  </div>


  <% end %>
</div>
      

app/views/tweets/index.html.erb
<%= render 'shared/navbar' %>

<h1 class="text-center">Tweets Index</h1>
<p class="link-center">
  <%= link_to 'Create new Tweet', new_tweet_path, class:"text-success " %>
</p>

<article class="main-flex">
<div class="containers center">
  <% @tweets.each do |tweet| %>


  <div class="tweets">
    <div class="cards">
      <div class="text-blue" style="background: antiquewhite">
        User: <%= link_to "#{tweet.user.name}", user_path(tweet.user), class: "text-black" %>
      </div>
      <div>
        <h5 class=""><%= tweet.title%></h5>
      </div>
      <hr />
      <p class=""><%= tweet.description %>.</p>
      <p>
        <%= tweet.reactions.count %> <%= (tweet.reactions.count) == 1 ? 'reaction' : 'reactions'%>
      </p>
    </div>
    <div>
      <p>
        <%= link_to 'Show', tweet_path(tweet), class:"btn btn-outline-primary" %> 
        <%= link_to 'Edit', edit_tweet_path(tweet), class:"btn btn-outline-success" %> 
        <%= link_to 'Delete', tweet_path(tweet), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-outline-danger" %>
      </p>
    </div>
    <div class="pl-5 py-2 card-footer text-muted">
      <div class="col-12 mt-3" id="new-comment">
        <%= render 'comments/form', object: tweet %>
      </div>
      <ul id="tweet-<%= tweet.id %>-comments-container" class="list-none">
        <% tweet.comments.last(3).reverse.each do |comment| %>
          <li class="comment-box cards"><%= comment.description %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <hr />
  <% end %>
</div>
</article>

app/views/tweets/new.html.erb
<%= render 'shared/navbar' %>

<h1 class="text-center">Create new Tweet</h1>
<div class="card text-center">
 

   <%= form_with scope: :tweet, url: tweets_path, local: true do |f| %>
  <div class="card-header">
    User:
  </div>
  <div class="card-body">
    <h5 class="card-title">
    <%= f.label :title, class: "col-1 col-form-label text-left" %> 
        
    <%= f.text_field :title, class: "col-6 col-form-label" %>
        
    </h5>
    <p class="card-text"> 
    <%= f.label :description, class: "col-2 col-form-label align-top" %>
           
    <%= f.text_area :description, rows: 8, class: "col-7 col-form-label ckeditor" %>

    </p>
    <p><%= f.submit class:"btn btn-primary"%></p>
  </div>


  <% end %>
</div>
      

app/views/tweets/show.html.erb
<%= render 'shared/navbar' %>
<h1 class="text-center">Tweets Show</h1>
<div class="container center">
  <div class="cards text-blue" style="background: antiquewhite">
    User: <%= @tweet.user.name if @tweet.user %>
  </div>
  <div>
    <div class="cards">
      <h5 class=""><%= @tweet.title%></h5>
      <hr />
      <p class=""><%= @tweet.description %></p>
    </div>
  </div>
  <p>
    <%= @tweet.reactions.count %> <%= (@tweet.reactions.count) == 1 ? 'reaction' : 'reactions'%>
  </p>
  <p>
    <% pre_reaction = @tweet.reactions.find { |reaction| reaction.user_id == current_user.id} %> 
    <% if pre_reaction %> 
      <%= button_to 'Unlike',tweet_reaction_path(@tweet, pre_reaction), remote: true, method: :delete %>
    <% else %> 
      <%= button_to 'Like', tweet_reactions_path(@tweet), remote: true, method: :post %> <% end %>
  </p>
  <div>
    <p>
      <%= link_to "Back to Index page", tweets_path, class: "btn-outline-dark"
      %>
    </p>
  </div>
  <div class="pl-5 py-2">
    <div class="col-12 mt-3" id="new-comment">
      <%= render 'comments/form', object: @tweet %>
    </div>
  </div>
  <div class="card-footer text-muted">
    <ul id="tweet-<%= @tweet.id %>-comments-container" class="list-none">
      <% @tweet.comments.reverse.each do |comment| %>
      <li class="">
        <%= render 'comments/show_comment', remote: true, object: comment %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'shared/navbar' %>

<h1 class="text-center">Users Index</h1>
<div class="card text-center">

   <% @users.each do |user| %>

  <div class="card-header">User: <%= user.name %></div>
  <div class="card-body">
    <h5 class="card-title"><%= user.name%></h5>
    <p class="card-text"><%= user.email %>.</p>
    <%= link_to 'Show', user_path(user), class:"btn btn-outline-primary" %>
  </div> 
  <% end %>
</div>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>

<h1 class="text-center">Users Show</h1>
<div class="card text-center" id="user_show">
  <div class="card-header">User: <%= @user.name %></div>
    <% pre_follow = @follows.where("follower_id=?", current_user.id).all.where("followed_user_id=?", @user.id) %> 
    <p data-id="<%= current_user.id %>" data-profile_id="<%= @user.id %>", data-pre_follow="<%= pre_follow.length %>" class="follows_ids">
    <% if current_user.id != @user.id %>
      <%= button_to 'Unfollow', user_follow_path(current_user.id), class: "unfollow-button hidden", method: :delete %>
      <%= button_to 'Follow', user_follows_path(@user), method: :post, class: 'follow-button hidden' %>
    <% end %>
    </p>
  <div class="card-body">
    <h5 class="card-title"><%= @user.name%></h5>
    <p class="card-text"><%= @user.email %></p>
  </div>
</div>